# Generated by Django 5.0.1 on 2024-01-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
                ('msg', models.CharField(max_length=20)),
            ],
        ),
    ]
