# Generated by Django 5.0.1 on 2024-01-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
