# Generated by Django 5.0.1 on 2024-01-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor_app', '0002_alter_info_outtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='msg',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
